apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: three-tier
type: Opaque
stringData:
  # MongoDB root user (USED BY MONGODB POD)
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin123

  # Backend app credentials (USED BY API POD)
  username: admin
  password: admin123
